apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{.Release.Name}}-secrets
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend-apps
  target:
    name: {{.Release.Name}}-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: backstage
        property: GITHUB_TOKEN
    - secretKey: ARGOCD_KEY
      remoteRef:
        key: backstage
        property: ARGOCD_KEY
    - secretKey: BACKSTAGE_KEY
      remoteRef:
        key: backstage
        property: BACKSTAGE_KEY
    - secretKey: AUTH_SESSION_SECRET
      remoteRef:
        key: backstage
        property: AUTH_SESSION_SECRET
