{{- if .Values.postgres.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{.Release.Name}}-pg-scheduled-backup
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: {{.Release.Name}}-pg
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
{{- end}}
