{{- if .Values.postgres.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend-pg
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: {{.Release.Name}}-pg-backup
          serviceAccountRef:
            audiences:
              - vault
            name: {{.Release.Name}}-pg-backup
      path: db-backup
      server: {{.Values.vault.url}}
      version: v2
{{- end}}
