{{- if .Values.postgres.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pg-minio-secret
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  data:
    - remoteRef:
        key: backstage-pg
        property: ACCESS_SECRET_KEY
      secretKey: ACCESS_SECRET_KEY
    - remoteRef:
        key: backstage-pg
        property: ACCESS_KEY_ID
      secretKey: ACCESS_KEY_ID
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault-backend-pg
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: pg-minio-secret
{{- end}}
